### ISSUE TITLE
Understanding the data files

### ISSUE THREAD

**Issue by ahmadmustafaanis** [Teddy-XiongGZ/MIRAGE#1]
Hi, first of all great work. Really appreciate it. 

I am trying to understand the work and reproduce it + test it on some new models. I am having some trouble understanding the given files.

1. There is a `benchmark.json` file with ground truth and answers
2. Then there are some golden files i.e `7B1_golden.json` which has question, link to relevant documents, ideal answer and so. 
3. Then there is prediction folder that has predictions for each model.

I want to understand the benchmark.json and golden files? Also, if I want to generate my prediction files for a new model how can I do that? I understand I have to use MedRAG repo for it but which files should I be using to do an apples to apples comparison of a new model with the old ones?

Thank you.

**Comment by gzxiong** [comment]
Hi, thanks for your interest in our work! Regarding your questions:

1. The benchmark.json is the only file you need to run your models on our MIRAGE benchmark. As you may notice, it contains all questions and corresponding answers to evaluate new models. 
2. Files such as 7B1_golden.json are the original data files we collected to build benchmark.json. For the benchmark evaluation of new models, you don't need these original files actually. Just ignore them.
3. The prediction folder contains the prediction results we ran for gpt-3.5 and gpt-4. It is just a reference to show how the results look.

We did not include the code we used for running the benchmark in this repo because we want this repo to be independent of the MedRAG toolkit. For an apples-to-apples comparison, you can use the demo code shown in the MedRAG repo and run the results iteratively on each question.
